task: ZS_fewrel
device: cuda:1
dataset:
  train: ./data/splits/zero_rte/fewrel/unseen_5_seed_0/train_convert.json
  dev: ../ABSAData/wang-BART/14res/dev_convert.json
  test: ../ABSAData/wang-BART/14res/test_convert.json
  max_len: 128
train:
  seed: 42
  lr: 1e-4
  batch_size: 32
  epochs: 20
  adam_epsilon: 1e-8
  weight_decay: 0
  warmup_ratio: 0
  gradient_accumulation_steps: 1
  gradient_clip_val: 1.0
eval:
  batch_size: 32
  max_answer_length: 12
  logit_threshold: 8
  filter_type: f1
  do_lower_case: 1
  use_nms: 1
  best_size: 20
  use_heuristics: 1
model:
  name: T5
  pretrain_model: ../../PretrainModel/t5-base
load: 1
checkpoints: ./outputs/14res/