for unseen in 5 10 15; do
  for seed in 0 1 2 3 4; do
    CUDA_VISIBLE_DEVICES=0 python main_rp.py --seed ${seed} --n_unseen ${unseen} --dataset fewrel
  done
done
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --n_unseen 10
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --n_unseen 10
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --n_unseen 10
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --n_unseen 10
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --n_unseen 10
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --n_unseen 15
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --n_unseen 15
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --n_unseen 15
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --n_unseen 15
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --n_unseen 15
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 1
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 2
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 3
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 4
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 1 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 2 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 3 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=0 python main.py --seed 4 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0  --reptile_m 3 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1  --reptile_m 3 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2  --reptile_m 3 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3  --reptile_m 3 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4  --reptile_m 3 --aux_loss_weight 0.3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0  --reptile_m 3 --aux_loss_weight 0.5
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1  --reptile_m 3 --aux_loss_weight 0.5
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2  --reptile_m 3 --aux_loss_weight 0.5
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3  --reptile_m 3 --aux_loss_weight 0.5
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4  --reptile_m 3 --aux_loss_weight 0.5
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0. --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0. --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0. --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0. --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0. --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0. --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0. --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0. --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0. --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0. --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.1
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0.1
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0.1
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0.1
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0.1
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.1 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0.1 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0.1 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0.1 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0.1 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.1 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0.1 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0.1 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0.1 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0.1 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0.2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0.2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0.2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0.2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.2 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0.2 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0.2 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0.2 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0.2 --reptile_m 2
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 0 --aux_loss_weight 0.2 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 1 --aux_loss_weight 0.2 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 2 --aux_loss_weight 0.2 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 3 --aux_loss_weight 0.2 --reptile_m 3
#CUDA_VISIBLE_DEVICES=1 python main.py --seed 4 --aux_loss_weight 0.2 --reptile_m 3